version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - dotnet tool install -g Amazon.Lambda.Tools
      # - command
  pre_build:
    commands:
       - export PATH="$PATH:/root/.dotnet/tools"
       - cd Test
      # - command
  build:
    commands:
       - dotnet-lambda package
  post_build:
    commands:
       - echo "$CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip"
       - echo $CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip
       - ls $CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1
artifacts:
  files:
     - "$CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip"
  name: lambda-build-$(AWS_REGION)-$(date +%Y%m%d_%H%m%ss)
  
  discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths