version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - dotnet tool install -g Amazon.Lambda.Tools
      # - command
  pre_build:
    commands:
       - export PATH="$PATH:/root/.dotnet/tools"
       - echo testando comandos
       - cd Test
      # - command
  build:
    commands:
       - dotnet-lambda package
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths