version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - echo $BUCKET
       - echo fileb://$CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip
       - echo "fileb://.$CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip"
       - echo fileb://"$CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip"
       - aws --version
       #- aws cloudformation package --template-file appspec.yml --s3-bucket $BUCKET --output-template-file appspecOutput.yaml --debug
       - dotnet tool install -g Amazon.Lambda.Tools
      # - command
  pre_build:
    commands:
       - export PATH="$PATH:/root/.dotnet/tools"
       - cd Test
      # - command
  build:
    commands:
       - dotnet-lambda package
  post_build:
    commands:
       - ls
       - echo $CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip
       - aws lambda update-function-code --function-name Test --zip-file file://bin/Release/netcoreapp2.1/Test.zip
       #- echo "************************************"
       #- echo $CODEBUILD_BUILD_ID
       #- echo $AWS_REGION
       #- echo $AWS_DEFAULT_REGION
       #- echo "************************************"
       - ls $CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1
artifacts:
  files:
     - "$CODEBUILD_SRC_DIR/Test/bin/Release/netcoreapp2.1/Test.zip"
     #- appspec.yml
     #- appspecOutput.yaml
  #name: build-$AWS_REGION-$(date +%Y%m%d_%H%m%ss).zip
  
  discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
